mapping:
  q: Quit
  ">": GoToEnd
  <: GoToStart
  q: Quit
  tab: NextSection
  backtab: PreviousSection
  y: CopyToClipBoard
  /: NewSearch
  esc: FocusOnTraces
  down: !NavigateDown
  up: !NavigateUp
  h: !NavigateLeft
  j: !NavigateDown
  L: !GoToRight
  H: !GoToLeft
  k: !NavigateUp
  l: !NavigateRight
  x: StopWebSocketServer
  X: StartWebSocketServer
  ?: Help
  p: ToggleDebug
  d: DeleteItem
  space: Select
  f: OpenFilter
  s: OpenSort
  "]": NextPane
  "[": PreviousPane
colors:
  surface-bg: rgb(32,32,32)
  surface-selected: rgb(92,201,157)
  surface-unselected: rgb(128,128,128)
