q: Quit
">": GoToEnd
<: GoToStart
q: Quit
tab: NextSection
backtab: PreviousSection
y: CopyToClipBoard
/: NewSearch
esc: FocusOnTraces
down: !NavigateDown
up: !NavigateUp
h: !NavigateLeft
j: !NavigateDown
k: !NavigateUp
l: !NavigateRight
