pub const RESPONSE_BODY_UNUSABLE_HORIZONTAL_SPACE: usize = 2;

pub const RESPONSE_BODY_UNUSABLE_VERTICAL_SPACE: usize = 2;

pub const RESPONSE_HEADERS_UNUSABLE_VERTICAL_SPACE: usize = 6;

pub const REQUEST_HEADERS_UNUSABLE_VERTICAL_SPACE: usize = 6;

pub const REQUEST_BODY_UNUSABLE_HORIZONTAL_SPACE: usize = 2;

pub const REQUEST_BODY_UNUSABLE_VERTICAL_SPACE: usize = 2;

pub const NETWORK_REQUESTS_UNUSABLE_VERTICAL_SPACE: usize = 4;
